site_name:  Torjoman | تُرجمان
docs_dir: 'source'
theme: 
  name: material
  features:
    - search.suggest 
    - search.highlight
    - content.tabs.link
  language: ar 
  direction: rtl
  palette: indigo
nav:
  - المقدمة: "index.md" 
  - جدول المحتويات: "pages/Contents-Table.md"
  - سجل المراجعة: "pages/Revision-History.md"
