site_name:  Torjoman | تُرجمان
docs_dir: 'source'
site_url: https://torojoman.aosus.dev

theme: 
  name: material
  custom_dir: overrides
  features:
    - search.suggest 
    - search.highlight
    - content.tabs.link
  language: ar 
  direction: rtl
  palette:
    primary: green
    accent: blue

nav:
  - المقدمة: "index.md" 
  - جدول المحتويات: "pages/Contents-Table.md"
  - سجل المراجعة: "pages/Revision-History.md"
