site_name:  Torjoman | تُرجمان
docs_dir: 'source'
site_url: https://torojoman.aosus.dev
repo_name: aosus/Torjoman
repo_url: https://github.com/aosus/Torjoman
edit_uri: https://github.com/aosus/Torjoman/_edit/dev/docs/source

theme: 
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - search.suggest 
    - search.highlight
    - content.tabs.link
  language: ar 
  direction: rtl
  palette:
  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
    primary: green
    accent: blue

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
    primary: green
    accent: blue

nav:
  - المقدمة: "index.md" 
  - المتطلبات البرمجية: "SRS.md"
