name: MkDocs-PR-test

on:
  workflow_dispatch:
  pull_request:
    types: [opened,edited,closed,reopened,synchronize] # Add closed
    branches: [ dev ]
    paths:
      - 'docs/**'
  pull_request_review:
    types: [edited, dismissed]


jobs:
  build-and-deploy-preview:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs # Use the docs directory https://stackoverflow.com/questions/58139175/running-actions-in-another-directory/63122434#63122434
    concurrency: # Only run one Job at a time
      group: ci-${{ github.ref }} 
      cancel-in-progress: true

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3 
      with:
        fetch-depth: '0'

    # setup python
    - name: Set up Python 3.10
      uses: actions/setup-python@v4.0.0
      with:
        python-version: 3.10.*

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install -U pip wheel
        python -m pip install -r requirements.txt
        git submodule update --init --recursive
        pip show mkdocs-material

    - name: mkdocs build
      run: mkdocs build --clean --verbose -d site

    - name: Cache pip files
      uses: actions/cache@v3.0.4
      env:
        cache-name: pip-reg
      with:
        path: $HOME/.cache/pip
        key: pip-reg