name: MkDocs-Build

on:
  push:
    paths:
      - 'docs/**'
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs # Use the docs directory https://stackoverflow.com/questions/58139175/running-actions-in-another-directory/63122434#63122434

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3 
      with:
        fetch-depth: '0'

    # setup python
    - name: Set up Python 3.10
      uses: actions/setup-python@v4.0.0
      with:
        python-version: 3.10.*

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install -U pip wheel
        python -m pip install -r requirements.txt
        git submodule update --init --recursive
        pip show mkdocs-material

    - name: mkdocs build
      run: mkdocs build --clean --verbose -d site

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: docs/site # The folder the action should deploy.
        clean-exclude: pr-preview/ # Exclude PR previews
        git-config-name: GitHub-actions[bot]
        git-config-email: 41898282+github-actions[bot]@users.noreply.github.com

    - name: Cache pip files
      uses: actions/cache@v3.0.4
      env:
        cache-name: pip-reg
      with:
        path: $HOME/.cache/pip
        key: pip-reg